### PR TITLE
Added Member of these Collections section 

### PR DESCRIPTION
**Pull request by Ole113**
Added the Member of these Collections section and updated the Dockerfile to remove the argument that was throwing the error.

### CODE REVIEW

**Comment by cjmyers** [comment]
@Ole113 Do you think you have fixed the docker build issue?

@benjhatch I wonder if building a docker image should be part of the tests.

**Comment by Ole113** [comment]
I removed the argument on yarn install that was giving the error in the Dockerfile so that should fix the docker build issue unless there's another error.

**Comment by cjmyers** [comment]
Just merged and it seems to be building the docker image now.

**Comment by benjhatch** [comment]
@Ole113 @cjmyers I'm glad it's working after removing frozen-lockfile. But, I'm a bit concerned that this is bad practice. Check this short article out to see the point of the command: https://nts.strzibny.name/freezing-dependencies-yarn-lock-frozen-lockfile/

**Comment by benjhatch** [comment]
I think the build was failing because there was a discrepancy between the yarn.lock file and the package.json file (meaning the installed dependencies differed from the dependencies/versions listed in the package.json file)

**Pull request merged**
